# Generated by Django 5.2.4 on 2025-08-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=3),
        ),
    ]
