# Generated by Django 5.2.4 on 2025-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_value',
            field=models.FloatField(blank=True, help_text='Current in Amps (only for sockets)', null=True),
        ),
    ]
