# Generated by Django 5.2.4 on 2025-08-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_pin',
            field=models.CharField(blank=True, help_text='Maps to the relay name (kitchen, living, light1, etc.)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='ESP32 Controller', max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='core.userprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllers', to='core.room')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.controller'),
        ),
        migrations.CreateModel(
            name='DeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overload', 'Overload'), ('short_circuit', 'Short Circuit'), ('offline', 'Device Offline')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.controller')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.controller')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
