# Generated by Django 5.2.4 on 2025-08-10 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_device_hardware_pin_controller_device_controller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware_pin',
            field=models.CharField(blank=True, help_text='Hardware pin name that ESP32 uses (kitchen, living, light1, etc.) - DO NOT change this after pairing', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='New Device', help_text='User-friendly display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicealert',
            name='alert_type',
            field=models.CharField(choices=[('overload', 'Overload'), ('short_circuit', 'Short Circuit'), ('offline', 'Device Offline'), ('high_current', 'High Current')], max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.device'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('controller', 'hardware_pin')},
        ),
    ]
