# Generated by Django 5.2.4 on 2025-08-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_devicecommand_max_retries_devicecommand_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=10)),
                ('action_type', models.CharField(choices=[('device_control', 'Device Control'), ('device_pairing', 'Device Pairing'), ('device_unpaired', 'Device Unpaired'), ('system_alert', 'System Alert'), ('user_action', 'User Action'), ('controller_status', 'Controller Status'), ('overload_detected', 'Overload Detected'), ('short_circuit', 'Short Circuit'), ('lockout_activated', 'Lockout Activated'), ('lockout_cleared', 'Lockout Cleared')], default='user_action', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='web', help_text='web, mobile, sms, esp32, system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.controller')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.device')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'), models.Index(fields=['log_type', 'created_at'], name='core_activi_log_typ_d02f5c_idx'), models.Index(fields=['action_type', 'created_at'], name='core_activi_action__e16858_idx'), models.Index(fields=['device', 'created_at'], name='core_activi_device__af6af2_idx')],
            },
        ),
    ]
