# Generated by Django 5.2.4 on 2025-08-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='previous_fault_state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
